spring:
  datasource:
    url: jdbc:mysql://47.108.29.69:40155/smartdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&autoReconnectForPools=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    maxActive: 11

mybatis:
  type-aliases-package: com.bzzn.dynamicdatasource
  mapper-locations: classpath:mapper/*Dao.xml
  config-location: classpath:mybatis-config.xml

# dynaimc-data-source
dynamic:
  datasource:
    pg:
      url: jdbc:postgresql://192.168.5.210:5432/postgres
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: 123456
      type: com.alibaba.druid.pool.DruidDataSource
    mysql:
      url: jdbc:mysql://localhost:3306/smartdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      type: com.alibaba.druid.pool.DruidDataSource